# Non Graded Challenge 3
### Albertus Magnus Adhi Wicaksono

In [56]:
import numpy as np

#### Soal 1 buat lah vektor di bawah ini dengan python

In [57]:
a = [17, 22, 19]
vector = np.array(a)
vector

array([17, 22, 19])

#### Soal 2 3 buah vector 3 dimensi bernilai

```
a = (17, 22, 19)
b = (10, 20, 11)
c = (5, 12, 9)

In [58]:
a = (17, 22, 19)
b = (10, 20, 11)
c = (5, 12, 9)

vect_a= np.array(a)
vect_b= np.array(b)
vect_c= np.array(c)

#### Soal 2a. Vector a + Vector b

In [59]:
vect_a + vect_b

array([27, 42, 30])

#### Soal 2b Vector b - Vector c

In [60]:
vect_b - vect_c

array([5, 8, 2])

#### Soal 2c Vector a dot Vector c

In [61]:
vect_a@vect_c

520

#### Soal 2d Vector A x Vector B

In [62]:
vect_a * vect_b

array([170, 440, 209])

#### Soal 2e Norm dari Vector A

In [63]:
vect_a = np.array([a])
np.linalg.norm(vect_a, 2)

33.67491648096547

#### Soal 2f Sudut antara Vector a dan Vector b

In [64]:
cos_theta = (vect_a@vect_b) / (np.linalg.norm(vect_a) * np.linalg.norm(vect_b))
cos_theta

array([0.975959])

In [65]:
rad = np.arccos(cos_theta)
rad

array([0.21971777])

In [66]:
degree = np.degrees(rad)
degree

array([12.58890066])

##### Sudut antara Vector A dan Vector B adalah 12.58890066 Derajat