In [2]:
!pip install pandas


NUMPY

In [3]:
import numpy as np


In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.empty(1)

array([1.])

In [10]:
print(np.arange(2,10,2))
print(np.arange(2))

[2 4 6 8]
[0 1]


In [11]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight/heigh**2

NameError: name 'heigh' is not defined

In [12]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_height = np.array(height)
np_weight = np.array(weight)
np_weight/np_height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [13]:
arr= np.array([1,2,3,4,5])
np.append(arr,([6,7,8]))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.delete(arr,1)

array([1, 3, 4, 5])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5])

In [26]:
array_1 = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10],
                     
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     
                     [21,22,23,24,25,],
                     [26,27,28,29,30]]])

print(array_1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [17]:
array_1.ndim

3

In [22]:
scalar= np.array(32)
print(scalar)
print (scalar.ndim)

32
0


In [23]:
vektor= np.array([1,2,3,4])
print (vektor)
print (vektor.ndim)

[1 2 3 4]
1


In [24]:
array_1.size

10

In [25]:
array_1.shape

(1, 2, 5)

In [27]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
b= a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [30]:
data = np.array([1,2,3])
print(data[1:2])

[2]


In [33]:
import numpy as np

In [34]:
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [35]:
arr = np.array(70)
print(arr)
print (arr.ndim)

70
0


In [36]:
arr = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

In [38]:
array_tes = np.array([[3,7,10,2], [3, 7, 10, 2]], ndmin=4)
print(array_tes)
print(array_tes.ndim)

[[[[ 3  7 10  2]
   [ 3  7 10  2]]]]
4


In [66]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[1,3])
print(arr.ndim)
print(arr.shape)

4
2
(2, 5)


In [55]:
arr = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])
print(arr[:, 1, 2])
print(arr.ndim)
print(arr.shape)

[ 6 12]
3
(2, 2, 3)


In [57]:
print(arr[0:, 1, 1])

[ 5 11]


In [58]:
print(arr[1:, 1, 1])

[11]


In [59]:
print(arr[:1, 1, 1])

[5]


In [64]:
print(arr[:1, 1, 1])

[5]


In [68]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[:3,:3])
print(arr.ndim)
print(arr.shape)

[[6 7 8]
 [1 2 3]]
2
(2, 5)


In [71]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[-2,-1])
print(arr.ndim)
print(arr.shape)

10
2
(2, 5)


In [72]:
arr=np.array([4, 5, 6, 7, 1, 2, 3])
print(arr[1:6:4])

[5 2]


In [73]:
arr=np.array([4, 5, 6, 7, 1, 2, 3])
print(arr[1:5:4])

[5]


In [74]:
arr = np.array([2, 2, 7, 4, 5, 6, 7, 8, 10])
print(arr[2:8:3])
print(arr[::3])

[7 6]
[2 4 7]


In [75]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:1, 1:3])

[[2 3]]


In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,])
newarr = arr.reshape(2, 2, -1)
print(newarr, "")
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
(2, 2, 3)
