# Matrix

#### Special Case vs Abstraksi

In [1]:
import numpy as np

In [3]:
data_1 = [1,2,3]
data_2 = [[1,2,3], [4,5]] ## bukan matrix karena jumlah elemen di dalamnya berbeda
data_3 = [[1,2,3], [4,5,6]]




In [6]:
vec = np.array(data_1)
vec


array([1, 2, 3])

In [7]:
mat = np.array(data_3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#definisi matriks

data= [[1,2], [3,4], [5,6], [7,8]] # pastikan jumlah elemen di dalam list sama
data_mat = np.array(data)
data_mat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
# contoh lain mendefinisikan matrix
v=np.array([[1,2,3], [1,0,3]]) 
print(v)

[[1 2 3]
 [1 0 3]]


# penjumlahan matrices

In [25]:
#operasi penjumlahan dan pengurangan matrix
A = [[1,2,3],
        [4,5,6],
        [7,8,9]]
A = np.array(A)

In [26]:
B = [[7,8,9],
    [9,8,7],
    [8,7,9]]
B = np.array(B)

In [27]:
# penjumlahan matriks
A + B

array([[ 8, 10, 12],
       [13, 13, 13],
       [15, 15, 18]])

In [28]:
# pengurangan matriks
A - B

array([[-6, -6, -6],
       [-5, -3, -1],
       [-1,  1,  0]])

In [31]:
#perkalian matrix - scalar
c = 5
A * c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
#pembagian matrix = scalar
A / c

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [29]:
# perkalian hadamard operation matriks
A * B

array([[ 7, 16, 27],
       [36, 40, 42],
       [56, 56, 81]])

In [30]:
# pembagian hadamard operation matriks
A / B

array([[0.14285714, 0.25      , 0.33333333],
       [0.44444444, 0.625     , 0.85714286],
       [0.875     , 1.14285714, 1.        ]])

In [33]:
# perkalian matrix-matrix
A@B

array([[ 49,  45,  50],
       [121, 114, 125],
       [193, 183, 200]])

In [34]:
F = [[7,8,9],
    [9,8,7],
    [8,7,9],
    [9,8,7],
    [8,7,9]]
F = np.array(F)

In [36]:
F@A

array([[102, 126, 150],
       [ 90, 114, 138],
       [ 99, 123, 147],
       [ 90, 114, 138],
       [ 99, 123, 147]])

In [40]:
A.dot(B)

array([[ 49,  45,  50],
       [121, 114, 125],
       [193, 183, 200]])

In [51]:
# perkalian matriks beda dimensi
C  = [[7,8],
    [9,8],
    [8,7]]

D = [[5,6,7],
    [8,9,10]]

C = np.array(C)
D = np.array(D)

In [52]:
C@D

array([[ 99, 114, 129],
       [109, 126, 143],
       [ 96, 111, 126]])

# Transpose

In [56]:
E = ([[1,2], [3,4], [5,6]])
E = np.array(E)


In [57]:
E.T

array([[1, 3, 5],
       [2, 4, 6]])

# Inverse Matriks

#### Hanya untuk matriks persegi
#### Matrix Singular tidak dapat di inverse

In [66]:
# Matriks H
H = ([[1,2], [3,4]])
H = np.array(H)
H

array([[1, 2],
       [3, 4]])

In [67]:
from numpy.linalg import inv #import fungsi linear algoritma dari numpy
inv_H = inv(H) # variabel inv_h berisikan inverse dari matrix H
inv_H # print inv_H

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
H @ inv_H

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# Determinan
### mendeterminasi apakah suatu matriks bisa di inverse atau tidak
#### Jika hasil determinan matris = 0 maka matriks tidak bisa di inverse

In [71]:
from numpy.linalg import det
det(H)

-2.0000000000000004

# Tensor
### Adalah matriks yang berada di dalam list

In [90]:
I = np.array([[1,2], [3,4], [1,1], [2,2]])
J = np.array([[5,6], [7,8], [2,2], [3,3]])
K = np.array([[5,6], [7,8], [2,2], [3,3]])
I


array([[1, 2],
       [3, 4],
       [1, 1],
       [2, 2]])

In [91]:
J

array([[5, 6],
       [7, 8],
       [2, 2],
       [3, 3]])

In [92]:
K

array([[5, 6],
       [7, 8],
       [2, 2],
       [3, 3]])

In [93]:
I.shape

(4, 2)

In [94]:
J.shape

(4, 2)

In [95]:
K.shape

(4, 2)

In [96]:
tensor = [I, J, K]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [3, 4],
        [1, 1],
        [2, 2]],

       [[5, 6],
        [7, 8],
        [2, 2],
        [3, 3]],

       [[5, 6],
        [7, 8],
        [2, 2],
        [3, 3]]])

In [97]:
tensor.shape #ada 2 matriks dengan ukuran 2 x 2

(3, 4, 2)

#### Vektor = 1-Dimensi Array = 1-Dimensi Tensor
#### Matriks = 2-Dimensi Array = 2-Dimensi Tensor
#### Lebih besar dari 2 dimensi = N-Dimension Array = Tensor